### PR TITLE
made it bigger and better

### PR DESCRIPTION
**Pull request by Exodus76**
pls accept this. i am your fren

### CODE REVIEW

**Comment by Exodus76** [comment]
> [image](https://user-images.githubusercontent.com/20737670/185680003-81be238a-3f5c-4b24-9252-0445595e6493.png)

**Review by tamamushi-iro — CHANGES_REQUESTED** [review]
Placing Game mode, Game difficulty and Start is not intuitive for the user. Placing these options in a Window File Menu would be better.

**Comment by tamamushi-iro** [comment]
Also, unacceptable format for Pull Request.

**Comment by Exodus76** [comment]
Made the above changes
Here is the updated GUI
[image](https://user-images.githubusercontent.com/20737670/185692074-37a35afe-a4f8-43c8-a283-09ede1e18ecf.png)

**Pull request merged**
